### PR TITLE
merge request

### PR DESCRIPTION
**Pull request by PrismaticDevs**

### CODE REVIEW

**Comment by Shman-Dee** [comment]
nice

**Review by Shman-Dee — APPROVED** [review]

**Review by Shman-Dee — APPROVED** [review]

**Review by PrismaticDevs — COMMENTED** [review]
A coinbase api fetch function was added

**Review by Shman-Dee — APPROVED** [review]
looks good

**Review by PrismaticDevs — COMMENTED** [review]
async function added

**Pull request merged**
